import type {
  ActivityItem,
  ArticleRecord,
  AutomationRule,
  DashboardSummary,
  KeywordRecord,
  PublishingLog,
} from "@patentzoom/seo-types";

export const dashboardSummary: DashboardSummary = {
  kpis: [
    { label: "Total keywords found", value: 1240, delta: "+14% this week", tone: "default" },
    { label: "Articles generated", value: 86, delta: "+12 this week", tone: "success" },
    { label: "Published blogs", value: 54, delta: "+7 this month", tone: "success" },
    { label: "Indexed pages", value: 31, delta: "3 pending", tone: "warning" },
    { label: "Organic traffic", value: "12.8k", delta: "+8.4%", tone: "default" },
    { label: "Automation status", value: "Healthy", delta: "6 queues active", tone: "success" },
  ],
  activityFeed: [
    {
      id: "act-1",
      title: "AI Writer completed",
      message: "Drafted \"AI patent filing strategy for startups\" with FAQ schema.",
      actor: "Article generation queue",
      status: "success",
      createdAt: "2026-05-11T10:20:00Z",
    },
    {
      id: "act-2",
      title: "Publishing retried",
      message: "WordPress media upload recovered after one retry.",
      actor: "Publishing queue",
      status: "warning",
      createdAt: "2026-05-11T09:45:00Z",
    },
    {
      id: "act-3",
      title: "Search Console sync",
      message: "Imported impressions and CTR snapshots for 28 published articles.",
      actor: "Reporting queue",
      status: "success",
      createdAt: "2026-05-11T08:00:00Z",
    },
  ],
  publishingLogs: [
    {
      id: "pub-1",
      articleTitle: "Provisional patent checklist for first-time founders",
      destination: "WordPress",
      status: "published",
      createdAt: "2026-05-11T07:32:00Z",
      detail: "Published with category and featured image.",
    },
    {
      id: "pub-2",
      articleTitle: "Office action response strategy for SaaS startups",
      destination: "WordPress",
      status: "processing",
      createdAt: "2026-05-11T08:10:00Z",
      detail: "Queued for editorial review before publishing.",
    },
    {
      id: "pub-3",
      articleTitle: "Patent filing cost breakdown for US inventors",
      destination: "WordPress",
      status: "failed",
      createdAt: "2026-05-11T09:15:00Z",
      detail: "Category resolution failed; retry available.",
    },
  ],
  automationRules: [
    {
      id: "auto-1",
      name: "Daily keyword research",
      schedule: "Every day at 07:00 IST",
      state: "active",
      lastRunAt: "2026-05-11T01:30:00Z",
      nextRunAt: "2026-05-12T01:30:00Z",
      description: "Discover low competition, high intent patent-law topics.",
    },
    {
      id: "auto-2",
      name: "Auto article generation",
      schedule: "Every day at 07:10 IST",
      state: "active",
      lastRunAt: "2026-05-11T01:40:00Z",
      nextRunAt: "2026-05-12T01:40:00Z",
      description: "Generate article briefs and drafts from approved keywords.",
    },
    {
      id: "auto-3",
      name: "Weekly SEO report",
      schedule: "Every Monday at 09:00 IST",
      state: "paused",
      lastRunAt: "2026-05-05T03:30:00Z",
      nextRunAt: "2026-05-12T03:30:00Z",
      description: "Send performance summary to operations.",
    },
  ],
  seoScore: 84,
  indexedPages: 31,
  organicTraffic: 12800,
};

export const keywordRows: KeywordRecord[] = [
  {
    id: "kw-1",
    keyword: "ai patent filing strategy for startups",
    cluster: "AI patents",
    intent: "High",
    volume: 1400,
    difficulty: 24,
    cpc: 8.2,
    trend: "Rising",
    competitionTier: "low",
    status: "selected",
  },
  {
    id: "kw-2",
    keyword: "provisional patent checklist",
    cluster: "Provisional patents",
    intent: "High",
    volume: 1200,
    difficulty: 19,
    cpc: 6.7,
    trend: "Stable",
    competitionTier: "low",
    status: "clustered",
  },
  {
    id: "kw-3",
    keyword: "office action response strategy",
    cluster: "USPTO process",
    intent: "Medium",
    volume: 800,
    difficulty: 33,
    cpc: 7.4,
    trend: "Stable",
    competitionTier: "medium",
    status: "discovered",
  },
  {
    id: "kw-4",
    keyword: "software patent mistakes to avoid",
    cluster: "Software patents",
    intent: "High",
    volume: 950,
    difficulty: 28,
    cpc: 9.1,
    trend: "Rising",
    competitionTier: "low",
    status: "writing",
  },
];

export const articleRows: ArticleRecord[] = [
  {
    id: "art-1",
    title: "AI patent filing strategy for startups",
    primaryKeyword: "ai patent filing strategy for startups",
    status: "Reviewing",
    seoScore: 88,
    readabilityScore: 73,
    updatedAt: "2026-05-11T10:20:00Z",
    authoringMode: "AI + optimization",
  },
  {
    id: "art-2",
    title: "How much does patent filing cost in the United States?",
    primaryKeyword: "patent filing cost in the united states",
    status: "Published",
    seoScore: 91,
    readabilityScore: 78,
    updatedAt: "2026-05-10T14:05:00Z",
    authoringMode: "AI + review",
  },
  {
    id: "art-3",
    title: "Design patent vs utility patent for consumer products",
    primaryKeyword: "design patent vs utility patent",
    status: "Indexed",
    seoScore: 86,
    readabilityScore: 75,
    updatedAt: "2026-05-09T12:15:00Z",
    authoringMode: "AI + refresh",
  },
];

export const publishingLogs: PublishingLog[] = dashboardSummary.publishingLogs;
export const automationRules: AutomationRule[] = dashboardSummary.automationRules;
export const activityFeed: ActivityItem[] = dashboardSummary.activityFeed;
